// docs/design/ocean-lightning-wizard/project/wizard/profile.jsx
// wizard/profile.jsx — post-setup app shell (nav) + Profile page.
const { useState: useProfState } = React;

const NODE_ID = "03f9a4c1d7e8…b21c";

// ── Shell: top nav (Profile / Lightning) + scroll area ──
function AppShell({ active, go, children }) {
  return (
    <div className="wz-content">
      <div className="app-nav">
        <span className="brand"><img src="assets/OCEAN-icon-white.svg" alt="OCEAN" /></span>
        <button className={`pill ${active === "profile" ? "active" : ""}`} onClick={() => go("profile")}>
          <Icon name="wallet" size={15} /> Profile
        </button>
        <button className={`pill ${active === "dashboard" ? "active" : ""}`} onClick={() => go("dashboard")}>
          <Icon name="bolt" size={15} /> Lightning
        </button>
        <span className="spacer" />
        <span className="acct"><span className="av">M</span> OCEAN Miner</span>
      </div>
      <div className="app-scroll">{children}</div>
    </div>
  );
}

const rhex = (n) => Array.from({ length: n }, () => "0123456789abcdef"[Math.floor(Math.random() * 16)]).join("");

function Profile({ guided, phrase, profile, setProfile, go, onReturnToSetup }) {
  const [revealed, setRevealed] = useProfState(false);
  const { addresses, offers } = profile;

  const addAddress = () => setProfile((p) => ({
    ...p,
    addresses: [...p.addresses, {
      id: "a" + Date.now(), label: "Payout address " + (p.addresses.length + 1),
      address: "bc1q" + rhex(38), offerId: p.offers[0] ? p.offers[0].id : null,
    }],
  }));
  const addOffer = () => setProfile((p) => ({
    ...p,
    offers: [...p.offers, { id: "o" + Date.now(), label: "Offer " + (p.offers.length + 1), value: "lno1" + rhex(92) }],
  }));
  const linkOffer = (addrId, offerId) => setProfile((p) => ({
    ...p, addresses: p.addresses.map((a) => (a.id === addrId ? { ...a, offerId: offerId || null } : a)),
  }));
  const offerLabel = (id) => { const o = offers.find((x) => x.id === id); return o ? o.label : "—"; };
  const linkCount = (id) => addresses.filter((a) => a.offerId === id).length;

  return (
    <React.Fragment>
      <div className="pf-head">
        <div className="pf-av">M</div>
        <div>
          <h1 className="pf-name">OCEAN Miner</h1>
          <p className="pf-id">
            Node {NODE_ID}
            <span className="db-chip ok"><span className="db-dot pulse" /> Verified</span>
          </p>
        </div>
      </div>

      {/* Onchain addresses */}
      <div className="pf-section">
        <div className="pf-section-h">
          <h2><Icon name="key" size={15} /> Onchain payout addresses</h2>
          <button className="pf-add" onClick={addAddress}><Icon name="key" size={13} /> Derive address</button>
        </div>
        <div className="pf-list">
          {addresses.map((a) => (
            <div className="pf-addr" key={a.id}>
              <div className="ic"><Icon name="key" size={16} /></div>
              <div className="meta">
                <p className="lbl">{a.label}</p>
                <p className="val">{a.address}</p>
              </div>
              <div className="link">
                <span className="pf-link-lbl">Linked offer</span>
                <select className="pf-select" value={a.offerId || ""} onChange={(e) => linkOffer(a.id, e.target.value)}>
                  <option value="">Not linked</option>
                  {offers.map((o) => <option key={o.id} value={o.id}>{o.label}</option>)}
                </select>
                <CopyBtn value={a.address} label="" />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Lightning offers */}
      <div className="pf-section">
        <div className="pf-section-h">
          <h2><Icon name="bolt" size={15} /> Lightning offers</h2>
          <button className="pf-add" onClick={addOffer}><Icon name="bolt" size={13} /> New offer</button>
        </div>
        <div className="pf-list">
          {offers.map((o) => (
            <div className="pf-offerrow" key={o.id}>
              <div className="ic"><Icon name="bolt" size={15} /></div>
              <div className="meta">
                <p className="lbl">{o.label}</p>
                <p className="val">{o.value}</p>
              </div>
              <span className="count">{linkCount(o.id)} address{linkCount(o.id) === 1 ? "" : "es"}</span>
              <CopyBtn value={o.value} label="" />
            </div>
          ))}
        </div>
      </div>

      {/* Recovery phrase */}
      <div className="pf-section">
        <div className="pf-section-h">
          <h2><Icon name="shield" size={15} /> Recovery phrase</h2>
        </div>
        <div className="pf-phrase">
          <div className="ph-top">
            <span className="t"><Icon name="lock" size={15} /> Your 24-word recovery phrase</span>
            <button className="wz-link muted" onClick={() => setRevealed((v) => !v)} style={{ fontSize: 12.5 }}>
              <Icon name={revealed ? "lock" : "eye"} size={14} />{revealed ? "Hide" : "Reveal"}
            </button>
          </div>
          {guided && (
            <p style={{ fontSize: 12.5, color: "#71717a", margin: "0 0 14px", lineHeight: 1.5 }}>
              This is the master backup for your wallet and all payout addresses. Never share it or take a screenshot.
            </p>
          )}
          <div className="wz-words-wrap">
            <div className="wz-words">
              {phrase.map((w, i) => (
                <div className="wz-word" key={i}><span className="wn">{i + 1}</span><span className="wt">{w}</span></div>
              ))}
            </div>
            {!revealed && (
              <div className="wz-blur" onClick={() => setRevealed(true)}>
                <div className="eye"><Icon name="eye" size={20} /></div>
                <div className="t">Tap to reveal</div>
                <div className="s">Make sure no one is watching</div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Shortcuts */}
      <div className="pf-section">
        <div className="pf-tiles">
          <button className="pf-tile" onClick={() => go("dashboard")}>
            <span className="tic"><Icon name="bolt" size={20} /></span>
            <div><h3>Lightning dashboard</h3><p>Track payout status and balances</p></div>
            <span className="arr"><Icon name="arrowR" size={18} /></span>
          </button>
          <button className="pf-tile" onClick={onReturnToSetup}>
            <span className="tic"><Icon name="refresh" size={20} /></span>
            <div><h3>Re-run setup</h3><p>Return to the setup wizard</p></div>
            <span className="arr"><Icon name="arrowR" size={18} /></span>
          </button>
        </div>
      </div>
    </React.Fragment>
  );
}

Object.assign(window, { AppShell, Profile });

// oceanln-web/src/lib/Profile.svelte
<script lang="ts">
  import Icon from "./ui/Icon.svelte";
  import Callout from "./ui/Callout.svelte";
  import { app, go, restart, client } from "./store.svelte";

  // profile is seeded before navigating here.
  const profile = $derived(app.profile!);
  let revealed = $state(false);
  let addingOffer = $state(false);

  function deriveAddress() {
    const n = profile.addresses.length + 1;
    // No "derive at index N" endpoint yet — this row is a placeholder until a
    // payout derives it. Linking still works.
    profile.addresses = [
      ...profile.addresses,
      { id: "a" + n, label: "Payout address " + n, address: "— derived on next payout —", offerId: profile.offers[0]?.id ?? null },
    ];
  }
  async function newOffer() {
    addingOffer = true;
    app.error = "";
    try {
      const r = await client().offer("Offer " + (profile.offers.length + 1));
      profile.offers = [
        ...profile.offers,
        { id: "o" + (profile.offers.length + 1), label: "Offer " + (profile.offers.length + 1), value: r.offer },
      ];
    } catch (e) {
      app.error = e instanceof Error ? e.message : String(e);
    } finally {
      addingOffer = false;
    }
  }
  function linkCount(offerId: string): number {
    return profile.addresses.filter((a) => a.offerId === offerId).length;
  }
</script>

<div class="app-scroll">
  <div class="pf-head">
    <div class="pf-av">O</div>
    <div>
      <h1 class="pf-name">My OCEAN wallet</h1>
      <p class="pf-id">
        {app.miningAddress.slice(0, 14)}…{app.miningAddress.slice(-6)}
        <span class="db-chip ok"><span class="db-dot"></span>Verified</span>
      </p>
    </div>
  </div>

  {#if app.error}
    <Callout kind="danger" icon="warn">{#snippet children()}{app.error}{/snippet}</Callout>
  {/if}

  <!-- Onchain payout addresses -->
  <div class="pf-section">
    <div class="pf-section-h">
      <h2><Icon name="key" size={15} /> Onchain payout addresses</h2>
      <button class="pf-add" onclick={deriveAddress}><Icon name="key" size={13} /> Derive address</button>
    </div>
    <div class="pf-list">
      {#each profile.addresses as addr}
        <div class="pf-addr">
          <div class="ic"><Icon name="key" size={16} /></div>
          <div class="meta">
            <div class="lbl">{addr.label}</div>
            <div class="val">{addr.address}</div>
          </div>
          <div class="link">
            <span class="pf-link-lbl">Linked offer</span>
            <select class="pf-select" bind:value={addr.offerId}>
              <option value={null}>Not linked</option>
              {#each profile.offers as o}
                <option value={o.id}>{o.label}</option>
              {/each}
            </select>
          </div>
        </div>
      {/each}
    </div>
  </div>

  <!-- Lightning offers -->
  <div class="pf-section">
    <div class="pf-section-h">
      <h2><Icon name="bolt" size={15} /> Lightning offers</h2>
      <button class="pf-add" onclick={newOffer} disabled={addingOffer}>
        <Icon name="spark" size={13} /> {addingOffer ? "Creating…" : "New offer"}
      </button>
    </div>
    <div class="pf-list">
      {#each profile.offers as o}
        <div class="pf-offerrow">
          <div class="ic"><Icon name="wallet" size={16} /></div>
          <div class="meta">
            <div class="lbl">{o.label}</div>
            <div class="val">{o.value}</div>
          </div>
          <span class="count">{linkCount(o.id)} address{linkCount(o.id) === 1 ? "" : "es"}</span>
        </div>
      {/each}
    </div>
  </div>

  <!-- Recovery phrase -->
  <div class="pf-section">
    <div class="pf-section-h"><h2><Icon name="lock" size={15} /> Recovery phrase</h2></div>
    <div class="pf-phrase">
      <div class="ph-top">
        <span class="t"><Icon name="key" size={15} /> Your 24 words</span>
        <button class="wz-copybtn" onclick={() => (revealed = !revealed)}>
          <Icon name="eye" size={13} /> {revealed ? "Hide" : "Reveal"}
        </button>
      </div>
      {#if revealed && app.phrase.length}
        <div class="wz-words">
          {#each app.phrase as word, i}
            <div class="wz-word"><span class="wn">{i + 1}</span><span class="wt">{word}</span></div>
          {/each}
        </div>
        <p style="font-size:12px;color:#52525b;margin:12px 0 0;display:flex;gap:7px;align-items:center"><Icon name="warn" size={13} /> Never share these words or take a screenshot.</p>
      {:else if revealed}
        <p style="font-size:13px;color:#71717a;margin:0">Phrase isn't held in this session — re-run setup or import to view it.</p>
      {:else}
        <p style="font-size:13px;color:#71717a;margin:0">Hidden. Reveal only when you're somewhere private.</p>
      {/if}
    </div>
  </div>

  <!-- Shortcuts -->
  <div class="pf-tiles">
    <button class="pf-tile" onclick={() => go("dashboard")}>
      <span class="tic"><Icon name="bolt" size={19} /></span>
      <div><h3>Lightning dashboard</h3><p>Monitor payouts, node status, and your offer.</p></div>
      <span class="arr"><Icon name="arrowR" size={16} /></span>
    </button>
    <button class="pf-tile" onclick={restart}>
      <span class="tic"><Icon name="refresh" size={19} /></span>
      <div><h3>Re-run setup</h3><p>Start the onboarding wizard again.</p></div>
      <span class="arr"><Icon name="arrowR" size={16} /></span>
    </button>
  </div>
</div>
