// docs/design/ocean-lightning-wizard/project/wizard/app.jsx
// wizard/app.jsx — window chrome, step rail, navigation, state, tweaks.
const { useState, useEffect } = React;

const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "density": "guided",
  "accent": "blue",
  "phraseLen": 24
}/*EDITMODE-END*/;

const ACCENTS = {
  orange: { c: "#f7931a", dim: "rgba(247,147,26,0.10)", line: "rgba(247,147,26,0.28)" },
  blue:   { c: "#4D6BFF", dim: "rgba(77,107,255,0.12)", line: "rgba(77,107,255,0.32)" },
};

// confirm-quiz positions must match ConfirmStep
const confirmPicks = (len) => (len >= 24 ? [3, 12, 20] : [2, 6, 10]);

// Seed the profile (onchain addresses + offers) from the setup results.
const seedProfile = (desc) => ({
  offers: [{ id: "o1", label: desc || "OCEAN mining payouts", value: ARTIFACTS.offer }],
  addresses: [{ id: "a1", label: "Primary payout", address: ARTIFACTS.address, offerId: "o1" }],
});

function App() {
  const [t, setTweak] = useTweaks(TWEAK_DEFAULTS);
  const guided = t.density === "guided";
  const phrase = PHRASE_24.slice(0, t.phraseLen);

  const [stepIndex, setStepIndex] = useState(0);
  const [surface, setSurface] = useState("wizard"); // 'wizard' | 'profile' | 'dashboard'
  const [mode, setMode] = useState("create");
  const [offerDescription, setOfferDescription] = useState("");
  const [profile, setProfile] = useState(null);
  const [revealed, setRevealed] = useState(false);
  const [backedUp, setBackedUp] = useState(false);
  const [importWords, setImportWords] = useState(() => Array(t.phraseLen).fill(""));
  const [answers, setAnswers] = useState({});
  const [provisionDone, setProvisionDone] = useState(false);
  const [signed, setSigned] = useState(false);
  const [verifyState, setVerifyState] = useState("idle");

  // apply accent globally
  useEffect(() => {
    const a = ACCENTS[t.accent] || ACCENTS.blue;
    const r = document.documentElement.style;
    r.setProperty("--wiz-accent", a.c);
    r.setProperty("--wiz-accent-dim", a.dim);
    r.setProperty("--wiz-accent-line", a.line);
  }, [t.accent]);

  // reset phrase-dependent state if length changes
  useEffect(() => {
    setImportWords(Array(t.phraseLen).fill(""));
    setAnswers({});
  }, [t.phraseLen]);

  const isImport = mode === "import";
  const skipConfirm = isImport; // imported phrases don't need re-confirmation

  // ── gating ──
  const importFilled = importWords.every((w) => w && w.length > 1);
  const confirmOK = confirmPicks(t.phraseLen).every((idx, qi) => answers[qi] === phrase[idx]);
  const canContinue = (() => {
    switch (STEPS[stepIndex].key) {
      case "phrase":  return isImport ? importFilled : (revealed && backedUp);
      case "confirm": return confirmOK;
      case "wallet":  return provisionDone;
      case "sign":    return signed;
      default:        return true;
    }
  })();

  const goNext = () => {
    let n = stepIndex + 1;
    if (STEPS[n] && STEPS[n].key === "confirm" && skipConfirm) n += 1;
    setStepIndex(Math.min(n, STEPS.length - 1));
  };
  const goBack = () => {
    let n = stepIndex - 1;
    if (STEPS[n] && STEPS[n].key === "confirm" && skipConfirm) n -= 1;
    setStepIndex(Math.max(n, 0));
  };
  const choose = (m) => { setMode(m); setStepIndex(1); };
  const restart = () => {
    setStepIndex(0); setMode("create"); setRevealed(false); setBackedUp(false);
    setImportWords(Array(t.phraseLen).fill("")); setAnswers({});
    setProvisionDone(false); setSigned(false); setVerifyState("idle");
    setSurface("wizard"); setOfferDescription(""); setProfile(null);
  };

  // navigate post-setup surfaces (seed profile on first visit)
  const go = (s) => {
    if (s === "profile" && !profile) setProfile(seedProfile(offerDescription));
    setSurface(s);
  };

  const railClick = (i) => { if (i < stepIndex) { if (STEPS[i].key === "confirm" && skipConfirm) return; setStepIndex(i); } };

  const key = STEPS[stepIndex].key;
  const stepEl = (() => {
    switch (key) {
      case "welcome": return <WelcomeStep guided={guided} onChoose={choose} />;
      case "phrase":  return <PhraseStep guided={guided} mode={mode} phrase={phrase} revealed={revealed} setRevealed={setRevealed} backedUp={backedUp} setBackedUp={setBackedUp} importWords={importWords} setImportWords={setImportWords} />;
      case "confirm": return <ConfirmStep key={t.phraseLen} guided={guided} phrase={phrase} answers={answers} setAnswers={setAnswers} />;
      case "wallet":  return <WalletStep guided={guided} provisionDone={provisionDone} setProvisionDone={setProvisionDone} offerDescription={offerDescription} setOfferDescription={setOfferDescription} />;
      case "sign":    return <SignStep guided={guided} signed={signed} setSigned={setSigned} />;
      case "done":    return <DoneStep guided={guided} verifyState={verifyState} setVerifyState={setVerifyState} onFinish={() => go("profile")} />;
    }
  })();

  const visibleSteps = STEPS.length - (skipConfirm ? 1 : 0);
  const humanIndex = stepIndex - (skipConfirm && stepIndex > 2 ? 1 : 0) + 1;

  return (
    <React.Fragment>
      <div className="wz-window">
        <div className="wz-body">
          {surface === "profile" || surface === "dashboard" ? (
            <AppShell active={surface} go={go}>
              {surface === "profile"
                ? <Profile guided={guided} phrase={phrase} profile={profile || seedProfile(offerDescription)} setProfile={setProfile} go={go} onReturnToSetup={() => setSurface("wizard")} />
                : <Dashboard guided={guided} offerDescription={offerDescription} />}
            </AppShell>
          ) : (
          <React.Fragment>
          {/* rail */}
          <div className="wz-rail">
            <div className="wz-rail-brand">
              <img src="assets/OCEAN-logo-white.svg" alt="OCEAN" />
              <span className="tag">Lightning</span>
            </div>
            {STEPS.map((s, i) => {
              const skipped = s.key === "confirm" && skipConfirm;
              const state = skipped ? "skip" : i < stepIndex ? "done" : i === stepIndex ? "active" : "";
              return (
                <div key={s.key} className={`wz-step ${state === "skip" ? "" : state}`}
                  style={{ cursor: i < stepIndex && !skipped ? "pointer" : "default", opacity: skipped ? 0.32 : 1 }}
                  onClick={() => railClick(i)}>
                  <div className="num">
                    {state === "done" ? <Icon name="check" size={13} stroke={2} />
                      : skipped ? "–" : i + 1}
                  </div>
                  <div className="lbl">{s.label}</div>
                </div>
              );
            })}
            <div className="wz-rail-foot">
              <div className="note">
                <Icon name="lock" size={13} />
                <span>Your keys and recovery phrase stay on your device.</span>
              </div>
            </div>
          </div>

          {/* content + footer */}
          <div className="wz-content">
            <div className="wz-scroll" key={key}>{stepEl}</div>
            <div className="wz-foot">
              {stepIndex > 0
                ? <Btn variant="ghost" icon="arrowL" onClick={goBack}>Back</Btn>
                : <span />}
              <span className="spacer" />
              <span className="wz-progress-text">Step {Math.min(humanIndex, visibleSteps)} of {visibleSteps}</span>
              {key === "welcome" && <span style={{ width: 4 }} />}
              {key === "done"
                ? (verifyState === "verified"
                    ? <Btn icon="refresh" onClick={restart}>Start over</Btn>
                    : null)
                : key !== "welcome"
                  ? <Btn iconRight="arrowR" disabled={!canContinue} onClick={goNext}>Continue</Btn>
                  : null}
            </div>
          </div>
          </React.Fragment>
          )}
        </div>
      </div>

      {/* Tweaks */}
      <TweaksPanel>
        <TweakSection label="Guidance" />
        <TweakRadio label="Explainers" value={t.density} options={["guided", "concise"]} onChange={(v) => setTweak("density", v)} />
        <TweakSection label="Wallet" />
        <TweakRadio label="Phrase length" value={t.phraseLen} options={[24, 12]} onChange={(v) => setTweak("phraseLen", v)} />
      </TweaksPanel>
    </React.Fragment>
  );
}

window.App = App;

// landfall-web/src/App.svelte
<script lang="ts">
  import Icon from "./lib/ui/Icon.svelte";
  import Button from "./lib/ui/Button.svelte";
  import Settings from "./lib/Settings.svelte";
  import Welcome from "./lib/wizard/Welcome.svelte";
  import Phrase from "./lib/wizard/Phrase.svelte";
  import Confirm from "./lib/wizard/Confirm.svelte";
  import Wallet from "./lib/wizard/Wallet.svelte";
  import Sign from "./lib/wizard/Sign.svelte";
  import Done from "./lib/wizard/Done.svelte";
  import Profile from "./lib/Profile.svelte";
  import Dashboard from "./lib/Dashboard.svelte";
  import {
    app, STEPS, stepKey, canContinue, continueStep, goBack, railClick,
    stepState, restart, go, visibleSteps, humanIndex, refreshHealth, bootstrap,
  } from "./lib/store.svelte";
  import { isTauri, openExternal } from "./lib/tauri";

  // Desktop only: the webview can't follow external `<a target="_blank">` links
  // (WKWebView treats them as inert; the CSP blocks navigating away). Intercept
  // every external http(s) link click app-wide and hand it to the OS browser via
  // the Rust opener — covers explorer links, ocean.xyz, mempool.space, etc.,
  // without each component having to know about Tauri. No-op in the browser build.
  $effect(() => {
    if (!isTauri()) return;
    const onClick = (e: MouseEvent) => {
      if (e.defaultPrevented || e.button !== 0) return;
      const a = (e.target as HTMLElement | null)?.closest?.("a");
      const href = a?.getAttribute("href") ?? "";
      if (/^https?:\/\//i.test(href)) {
        e.preventDefault();
        void openExternal(href);
      }
    };
    document.addEventListener("click", onClick);
    return () => document.removeEventListener("click", onClick);
  });

  const ACCENTS = {
    orange: { c: "#f7931a", dim: "rgba(247,147,26,0.10)", line: "rgba(247,147,26,0.28)" },
    blue: { c: "#4D6BFF", dim: "rgba(77,107,255,0.12)", line: "rgba(77,107,255,0.32)" },
  };

  // Apply the accent globally whenever it changes.
  $effect(() => {
    const a = ACCENTS[app.accent];
    const r = document.documentElement.style;
    r.setProperty("--wiz-accent", a.c);
    r.setProperty("--wiz-accent-dim", a.dim);
    r.setProperty("--wiz-accent-line", a.line);
  });

  // Health check on load + whenever the base URL changes.
  $effect(() => {
    void app.base;
    refreshHealth();
  });

  // Bootstrap on launch AND whenever the credentials change. In the browser
  // build, `app.token` starts empty in production — the first bootstrap will
  // 401 and silently leave the user in onboarding. When they paste the
  // bearer token (or change the base URL) in Settings, re-run bootstrap so
  // an already-configured wallet is detected and the user lands on the
  // restored profile/offer instead of being asked to generate a new one.
  //
  // Tauri build: `app.token` is unused (in-process IPC has no token) and
  // doesn't change at runtime, so the effect re-runs once on mount only.
  $effect(() => {
    void app.token;
    void app.base;
    void bootstrap();
  });
</script>

<!-- Full-frame app surface (no OS window chrome); branding lives in the rail / top nav. -->
<div class="wz-window">
  <div class="wz-body">
    {#if app.surface === "profile" || app.surface === "dashboard"}
      <div style="flex:1;display:flex;flex-direction:column;min-width:0">
        <div class="app-nav">
          <div class="brand"><img src="/assets/OCEAN-logo-white.svg" alt="OCEAN" /></div>
          <button class="pill {app.surface === 'profile' ? 'active' : ''}" onclick={() => go("profile")}><Icon name="key" size={14} /> Profile</button>
          <button class="pill {app.surface === 'dashboard' ? 'active' : ''}" onclick={() => go("dashboard")}><Icon name="bolt" size={14} /> Lightning</button>
          <span class="spacer"></span>
          <span class="acct"><span class="av">O</span> My wallet</span>
        </div>
        {#if app.surface === "profile"}<Profile />{:else}<Dashboard />{/if}
      </div>
    {:else}
      <!-- rail -->
      <div class="wz-rail">
        <div class="wz-rail-brand"><img src="/assets/OCEAN-logo-white.svg" alt="OCEAN" /><span class="tag">Lightning</span></div>
        {#each STEPS as s, i}
          {@const st = stepState(i)}
          <div
            class="wz-step {st === 'skip' ? '' : st}"
            style="cursor:{i < app.stepIndex && st !== 'skip' ? 'pointer' : 'default'};opacity:{st === 'skip' ? 0.32 : 1}"
            onclick={() => railClick(i)}
            onkeydown={(e) => e.key === "Enter" && railClick(i)}
            role="button"
            tabindex="-1"
          >
            <div class="num">
              {#if st === "done"}<Icon name="check" size={13} stroke={2} />
              {:else if st === "skip"}–
              {:else}{i + 1}{/if}
            </div>
            <div class="lbl">{s.label}</div>
          </div>
        {/each}
        <div class="wz-rail-foot">
          <div class="note"><Icon name="lock" size={13} /><span>Your keys and recovery phrase stay on your device.</span></div>
        </div>
      </div>

      <!-- content + footer -->
      <div class="wz-content">
        <div class="wz-scroll">
          {#key app.stepIndex}
            {#if stepKey() === "welcome"}<Welcome />
            {:else if stepKey() === "phrase"}<Phrase />
            {:else if stepKey() === "confirm"}<Confirm />
            {:else if stepKey() === "wallet"}<Wallet />
            {:else if stepKey() === "sign"}<Sign />
            {:else}<Done />{/if}
          {/key}
        </div>
        <div class="wz-foot">
          {#if app.stepIndex > 0}
            <Button variant="ghost" icon="arrowL" onclick={goBack}>{#snippet children()}Back{/snippet}</Button>
          {/if}
          <span class="spacer"></span>
          <span class="wz-progress-text">Step {Math.min(humanIndex(), visibleSteps())} of {visibleSteps()}</span>
          {#if stepKey() === "done"}
            {#if app.submitted}
              <Button icon="refresh" onclick={restart}>{#snippet children()}Start over{/snippet}</Button>
            {/if}
          {:else if stepKey() !== "welcome"}
            <Button iconRight="arrowR" disabled={!canContinue() || app.busy} onclick={continueStep}>{#snippet children()}Continue{/snippet}</Button>
          {/if}
        </div>
      </div>
    {/if}
  </div>
</div>

<Settings />
