// oceanln-web/src/lib/Dashboard.svelte
<script lang="ts">
  import Icon from "./ui/Icon.svelte";
  import { app } from "./store.svelte";
  import { DASH, MCP } from "./data";

  let mcpOn = $state(true);
  let copied = $state(false);
  function copyCmd() {
    navigator.clipboard?.writeText(MCP.addCmd).catch(() => {});
    copied = true;
    setTimeout(() => (copied = false), 1600);
  }
  const offerValue = $derived(app.offer || "lno1…(create a wallet first)");
</script>

<div class="db-wrap">
  <div class="db-top">
    <div>
      <h1>Payout dashboard</h1>
      <p class="sub">Monitoring your OCEAN Lightning payouts · <span style="color:#52525b">illustrative data</span></p>
    </div>
    <span class="db-chip ok"><span class="db-dot pulse"></span>{DASH.node.status}</span>
  </div>

  <div class="db-stats">
    <div class="db-stat"><div class="l">Pending</div><div class="v accent">{DASH.pendingSats}<span class="u">sats</span></div></div>
    <div class="db-stat"><div class="l">Total paid</div><div class="v">{DASH.totalBtc}<span class="u">BTC</span></div></div>
    <div class="db-stat"><div class="l">Payouts</div><div class="v">{DASH.payoutsCount}</div></div>
    <div class="db-stat"><div class="l">Next ETA</div><div class="v">{DASH.nextEta}</div></div>
  </div>

  <div class="db-panel">
    <div class="db-panel-h">
      <h3><Icon name="bolt" size={15} /> Recent payouts</h3>
      <span class="meta">{DASH.node.enclave} · up {DASH.node.uptime}</span>
    </div>
    <table class="db-table">
      <thead><tr><th>Time</th><th class="r">Amount</th><th class="r">Status</th></tr></thead>
      <tbody>
        {#each DASH.payouts as p}
          <tr>
            <td>{p.time}</td>
            <td class="r amt">{p.sats}{p.sats !== "—" ? " sats" : ""}</td>
            <td class="r"><span class="db-status {p.status === 'settled' ? 'settled' : 'inflight'}">{p.status}</span></td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>

  <div class="db-grid2">
    <div class="db-panel db-offercard">
      <div class="db-panel-h"><h3><Icon name="wallet" size={15} /> Your offer</h3></div>
      <div class="db-panel-b">
        <p class="od">{app.offerDescription || "OCEAN mining payouts"}</p>
        <p class="ov">{offerValue}</p>
        <span class="db-chip muted">BOLT12 · reusable</span>
      </div>
    </div>

    <div class="db-panel">
      <div class="db-panel-h">
        <h3><Icon name="spark" size={15} /> AI access (MCP)</h3>
        <button class="db-toggle {mcpOn ? 'on' : ''}" onclick={() => (mcpOn = !mcpOn)} aria-label="toggle MCP"><span class="knob"></span></button>
      </div>
      <div class="db-panel-b">
        <p class="db-mcp-intro">
          Connect your payout node to Claude Code or any MCP client. <span style="color:#52525b">(Illustrative — `oceanln mcp serve` is not implemented yet.)</span>
        </p>
        <div class="db-code">
          <code><span class="pre">$ </span>{MCP.addCmd}</code>
          <button class="wz-copybtn {copied ? 'copied' : ''}" onclick={copyCmd}><Icon name={copied ? "check" : "copy"} size={13} />{copied ? "Copied" : "Copy"}</button>
        </div>
        <p class="db-cap-h">What it can do</p>
        <ul class="db-caps">
          {#each MCP.tools as t}
            <li class="db-cap"><Icon name="check" size={15} />{t}</li>
          {/each}
        </ul>
        <div class="db-clients"><Icon name="lock" size={13} /> {MCP.cannot}</div>
      </div>
    </div>
  </div>
</div>

// docs/design/ocean-lightning-wizard/project/wizard/dashboard.jsx
// wizard/dashboard.jsx — post-setup payout dashboard + MCP (AI access) panel.
const { useState: useDashState } = React;

function StatusChip({ kind = "ok", pulse, children }) {
  return (
    <span className={`db-chip ${kind}`}>
      <span className={`db-dot ${pulse ? "pulse" : ""}`} />{children}
    </span>
  );
}

function McpPanel({ guided }) {
  const [on, setOn] = useDashState(true);
  return (
    <div className="db-panel db-offercard">
      <div className="db-panel-h">
        <h3><Icon name="link" size={16} style={{ color: "var(--wiz-accent)" }} /> AI access · MCP</h3>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <StatusChip kind={on ? "live" : "muted"} pulse={on}>{on ? "Serving" : "Off"}</StatusChip>
          <button className={`db-toggle ${on ? "on" : ""}`} onClick={() => setOn((v) => !v)} aria-label="Toggle MCP server">
            <span className="knob" />
          </button>
        </div>
      </div>
      <div className="db-panel-b">
        <p className="db-mcp-intro">
          Connect your payout node to <b style={{ color: "#fafafa" }}>Claude Code</b> or any
          MCP-compatible assistant. The AI can read your payout status and help you manage
          your setup — over a local, self-hosted server.
        </p>

        <div style={{ opacity: on ? 1 : 0.4, pointerEvents: on ? "auto" : "none" }}>
          <div className="db-cap-h">Add to Claude Code</div>
          <div className="db-code">
            <code><span className="pre">$ </span>{MCP.addCmd}</code>
            <CopyBtn value={MCP.addCmd} />
          </div>

          <div className="db-cap-h">What the assistant can do</div>
          <ul className="db-caps">
            {MCP.tools.map((t) => (
              <li className="db-cap" key={t}><Icon name="check" size={15} stroke={2} />{t}</li>
            ))}
          </ul>
          <p style={{ fontSize: 12, color: "#52525b", display: "flex", gap: 8, alignItems: "flex-start", margin: "14px 0 0" }}>
            <Icon name="lock" size={13} style={{ marginTop: 1, flexShrink: 0 }} /> {MCP.cannot}
          </p>

          <div className="db-clients">
            <span className="db-dot pulse" style={{ color: "#22c55e" }} />
            1 client connected · Claude Code
          </div>
        </div>
      </div>
    </div>
  );
}

function OfferPanel({ offerDescription }) {
  return (
    <div className="db-panel db-offercard">
      <div className="db-panel-h">
        <h3><Icon name="bolt" size={16} style={{ color: "var(--wiz-accent)" }} /> Your Lightning offer</h3>
        <span className="db-chip muted">BOLT12</span>
      </div>
      <div className="db-panel-b">
        <p className="od">Description</p>
        <p className="ov">{offerDescription || "OCEAN mining payouts"}</p>
        <p className="od">Offer (lno1…)</p>
        <div className="db-code">
          <code style={{ maxHeight: 70, overflow: "hidden" }}>{ARTIFACTS.offer}</code>
          <CopyBtn value={ARTIFACTS.offer} />
        </div>
        <div style={{ height: 12 }} />
        <p className="od">Payout address</p>
        <div className="db-code">
          <code>{ARTIFACTS.address}</code>
          <CopyBtn value={ARTIFACTS.address} />
        </div>
      </div>
    </div>
  );
}

function Dashboard({ guided, offerDescription }) {
  return (
    <React.Fragment>
        <div className="db-top">
          <div>
            <h1>Lightning payouts</h1>
            <p className="sub">Your OCEAN mining rewards, paid over Lightning.</p>
          </div>
          <StatusChip kind="ok" pulse>Node online</StatusChip>
        </div>

        <div className="db-stats">
          <div className="db-stat">
            <div className="l"><Icon name="bolt" size={12} /> Pending balance</div>
            <div className="v">{DASH.pendingSats} <span className="u">sats</span></div>
          </div>
          <div className="db-stat">
            <div className="l"><Icon name="wallet" size={12} /> Total received</div>
            <div className="v">{DASH.totalBtc} <span className="u">BTC</span></div>
          </div>
          <div className="db-stat">
            <div className="l"><Icon name="check" size={12} /> Payouts</div>
            <div className="v">{DASH.payoutsCount}</div>
          </div>
          <div className="db-stat">
            <div className="l"><Icon name="refresh" size={12} /> Next payout</div>
            <div className="v accent">{DASH.nextEta}</div>
          </div>
        </div>

        <div className="db-panel">
          <div className="db-panel-h">
            <h3>Recent payouts</h3>
            <span className="meta">{DASH.node.enclave} · up {DASH.node.uptime}</span>
          </div>
          <table className="db-table">
            <thead>
              <tr><th>Time</th><th>Status</th><th className="r">Amount</th></tr>
            </thead>
            <tbody>
              {DASH.payouts.map((p, i) => (
                <tr key={i}>
                  <td>{p.time}</td>
                  <td>
                    <span className={`db-status ${p.status === "settled" ? "settled" : "inflight"}`}>
                      <span className="db-dot" />{p.status === "settled" ? "Settled" : "In-flight"}
                    </span>
                  </td>
                  <td className="r amt">{p.sats === "—" ? "—" : `${p.sats} sats`}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="db-grid2">
          <OfferPanel offerDescription={offerDescription} />
          <McpPanel guided={guided} />
        </div>
    </React.Fragment>
  );
}

Object.assign(window, { Dashboard });
